const $=s=>document.querySelector(s), steps=[...document.querySelectorAll('.step')];let state={name:'',date:null,theme:null,birthday:false,age:0,next:null},sel=null,view=new Date();
function show(id){steps.forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0)}
$('#welcome .gold').onclick=()=>{$('#watermark').classList.add('visible');show('nameStep')};$('#name').oninput=()=>$('#nameStep .next').disabled=!$('#name').value.trim();$('#nameContinue').onclick=()=>{if(!$('#name').value.trim())return;show('dateStep')};
$('#dateDisplay').onclick=()=>$('#calendar').classList.toggle('open');$('#prev').onclick=()=>{view.setMonth(view.getMonth()-1);cal()};$('#next').onclick=()=>{view.setMonth(view.getMonth()+1);cal()};function cal(){let y=view.getFullYear(),m=view.getMonth();$('#monthLabel').textContent=view.toLocaleDateString('en-US',{month:'long',year:'numeric'});let box=$('#days');box.innerHTML='';let start=new Date(y,m,1).getDay();start=start===0?6:start-1;let total=new Date(y,m+1,0).getDate();for(let i=0;i<start;i++)box.appendChild(document.createElement('div'));for(let d=1;d<=total;d++){let e=document.createElement('div');e.className='day click';e.textContent=d;let t=new Date();if(d===t.getDate()&&m===t.getMonth()&&y===t.getFullYear())e.classList.add('today');if(sel&&d===sel.getDate()&&m===sel.getMonth()&&y===sel.getFullYear())e.classList.add('selected');e.onclick=()=>{sel=new Date(y,m,d);$('#dateDisplay').innerHTML=sel.toLocaleDateString('en-US',{day:'numeric',month:'long',year:'numeric'})+' <span>✓</span>';$('#dateContinue').disabled=false;cal()};box.appendChild(e)}}cal();$('#dateContinue').onclick=()=>show('themeStep');
document.querySelectorAll('.theme').forEach(b=>b.onclick=()=>{document.querySelectorAll('.theme').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.theme=b.dataset.theme;document.body.classList.toggle('female',state.theme==='female');document.body.classList.toggle('male',state.theme==='male');$('#themeContinue').disabled=false});
function age(b,n){let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a}function nextBD(now,b){let x=new Date(now.getFullYear(),b.getMonth(),b.getDate(),now.getHours(),now.getMinutes(),now.getSeconds(),now.getMilliseconds());if(x<=now)x=new Date(now.getFullYear()+1,b.getMonth(),b.getDate(),now.getHours(),now.getMinutes(),now.getSeconds(),now.getMilliseconds());return x}
async function prepare(){state.name=$('#name').value.trim();state.date=sel;let now=new Date();state.birthday=now.getMonth()===sel.getMonth()&&now.getDate()===sel.getDate();state.age=age(sel,now);state.next=nextBD(now,sel);show('checkingStep');let bar=$('#checkbar'),txt=$('#checkingText');for(const [i,t] of ['Reading your date...','Comparing today...','Calculating your age...','Preparing your theme...'].entries()){txt.textContent=t;bar.style.width=(i+1)*25+'%';await new Promise(r=>setTimeout(r,650))}if(state.birthday){$('#bName').textContent=state.name;$('#age').textContent=state.age;$('#daysLived').textContent=Math.floor((now-sel)/86400000).toLocaleString();document.querySelectorAll('.female-only').forEach(x=>x.style.display=state.theme==='female'?'block':'none');document.querySelectorAll('.male-only').forEach(x=>x.style.display=state.theme==='male'?'block':'none');show('birthdayStep')}else{$('#nName').textContent=state.name;$('#normalAge').textContent=state.age;$('#nextBirthdayDate').textContent=state.next.toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'});show('normalStep');countdown()}}
$('#themeContinue').onclick=prepare;$('#normalStep .next').onclick=()=>{show('normalFunStep');countdown()};$('#normalFunStep .next').onclick=()=>{$('#finalTitle').textContent=`Your day will come, ${state.name}.`;$('#finalText').textContent='Until then, keep collecting moments worth remembering. When the date arrives, this little page will know.';show('finalStep')};$('#birthdayStep .next').onclick=()=>{$('#mName').textContent=state.name;show('messageStep')};$('#messageStep .next').onclick=()=>show('wishStep');
let timer;function countdown(){clearInterval(timer);const tick=()=>{let now=new Date(),target=nextBD(now,state.date),sec=Math.max(0,Math.floor((target-now)/1000)),d=Math.floor(sec/86400),h=Math.floor(sec%86400/3600),m=Math.floor(sec%3600/60),s=sec%60;$('#countdown').textContent=`${d}d ${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`};tick();timer=setInterval(tick,1000)}
$('#wish').onclick=()=>{$('#wish').disabled=true;$('#wish').textContent='✦ Wish Received';setTimeout(()=>{$('#wishResult').textContent='Your wish is yours alone. Keep it safe.';$('#wishContinue').hidden=false},700)};$('#wishContinue').onclick=()=>{$('#finalTitle').textContent=`Here's to another year, ${state.name}.`;$('[id=finalText]').textContent='Make it yours. Keep the good moments close, leave room for new ones, and enjoy the chapter that starts today.';show('finalStep')};const url='https://iam-steveee.github.io/surprise';$('#shareUrl').value=url;$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(url);$('#copy').textContent='Copied!';setTimeout(()=>$('#copy').textContent='Copy',1500)}catch{prompt('Copy this link:',url)}};$('#share').onclick=async()=>{if(navigator.share){try{await navigator.share({title:'A Birthday Surprise',text:'I made a birthday surprise for you.',url})}catch{}}else{await navigator.clipboard.writeText(url);$('#share').textContent='Link Copied!'}};$('#again').onclick=()=>location.reload();
document.querySelectorAll('.next[data-next]').forEach(b=>{if(!b.id)b.onclick=()=>show(b.dataset.next)});
